### PR TITLE
N0ury master

### PR DESCRIPTION
**Pull request by niccokunzmann**
This updates https://github.com/collective/icalendar/pull/502 to have a merge with master.

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Interesting ... There are new Jenkins jobs appearing. I can understand the changelog one. I will experiment with the others.

**Comment by niccokunzmann** [comment]
This PR does indeed fix #348. However, I wonder for the tests how the values can be accessed:

```
E           TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```
Is now:
```
>       assert freebusy["ORGANIZER"]["CN"] == "Sixt SE"
E       TypeError: string index indices must be integers or slices, not str
```
for this line:
```
ORGANIZER;CN=Sixt SE
```

**Comment by niccokunzmann** [comment]
I fixed the test with the help of the documentation. The current error is that the parameter is missing a character. 

```
AssertionError: assert 'Sixt S' == 'Sixt SE'
```
On it ...

**Comment by niccokunzmann** [comment]
@mauritsvanrees The plone PR tests were added and I do not know if they work for this module. They just appeared. I will run them but I do not know if they actually mean something. Could you check that they use the code from this PR when they run?

**Comment by niccokunzmann** [comment]
@mauritsvanrees The 3.8 test fails.
https://jenkins.plone.org/job/pull-request-6.0-3.8/2576/robot/report/robot_report.html#totals
I am not really clear about why and how this bug fix contributed to that. I will wait a bit for a reply. If I merge this, then I will wait a bit with the release if the tests fail.

**Comment by mauritsvanrees** [comment]
I see the Jenkins tests pass on Python 3.9, 3.10 and 3.11 and only fail on 3.8.  The two failures are in robot framework tests, and there can be some instability in there.  Looks unrelated.

But really, the Jenkins jobs should not run.  We have a GitHub Actions test in this repo that uses Plone, and that should be enough.  I think I or someone else has pushed a button to automatically re-enable these tests on lots of repositories.
I have deleted some web hooks in the settings.  The Jenkins tests should not be started for new PRs now.

For the record, the Jenkins jobs *do* use the branch from this PR.  See the [3.8 console](https://jenkins.plone.org/job/pull-request-6.0-3.8/2576/consoleFull):

```
mr.developer: Cloned 'icalendar' with git using branch 'N0ury-master' from 'https://github.com/niccokunzmann/icalendar.git'.
```

So: should be fine to merge and release, but I will leave both to you.  Thanks!

**Comment by niccokunzmann** [comment]
@mauritsvanrees Thanks for the clarification! I like the changelog test by the way. That is a handy reminder. If you like to enable this again, that should be ok to try out.

**Pull request merged**
