### PR TITLE
Add scripts and tests to reproduce fuzzer errors in pytest

### PR DESCRIPTION
**Pull request by niccokunzmann**
- move fuzzing tests in to test folder
- create a script that runs the fuzzer and extracts the test case if the test fails

### CODE REVIEW

**Comment by niccokunzmann** [comment]
My intention is to create small pull requests like this one: https://github.com/niccokunzmann/icalendar/pull/2
Most OSS FUZZ errors depend on ICS files. These errors get reproduced though these pull requests. Then, we can fix, review and reproduce them locally with pytest. Probably, there is more to do about this. This is my current state of work.

**Comment by niccokunzmann** [comment]
My idea is that I create the infrastructure to reproduce the tests easily. From there on, each time I get an email about a new error, I will create a PR with the error so it can be reproduced.

**Comment by capuanob** [comment]
@niccokunzmann This is very cool! I just want to make sure of a few things

1. Did you test this locally with a checked out OSSFuzz (instructions [here](https://google.github.io/oss-fuzz/getting-started/new-project-guide/#testing-locally)) to make sure that it doesn't break the OSSFuzz integration?
2. Also, I wonder if there is any performance impact to the fuzz-testing with the addition of stdout prints? I'd imagine its minimal, but worth confirming the reported exec/s before and after the changes when running locally

**Comment by niccokunzmann** [comment]
> id you test this locally with a checked out OSSFuzz (instructions [here](https://google.github.io/oss-fuzz/getting-started/new-project-guide/#testing-locally)) to make sure that it doesn't break the OSSFuzz integration?

Yes, I did that. This allowed me to extract the ICS file used.

> Also, I wonder if there is any performance impact to the fuzz-testing with the addition of stdout prints?

That is minimal (a few milliseconds if I look at it). The corpus has a few files in it. Printing these does not make is slower. Running the fuzzer and preparing the fuzzing tests take most of the time.

**Comment by ennamarie19** [comment]
LGTM!

**Pull request closed without merging**
