### PR TITLE
use tox to build the documentation

### PR DESCRIPTION
**Pull request by niccokunzmann**
This is a start to build the documentation using tox.

### CODE REVIEW

**Comment by niccokunzmann** [comment]
I would like to use tox extensively in documentation and such so that testing the package becomes easy and contributors are inclined to contribute tested code. This is a patch for tox and documentation building.

**Review by mauritsvanrees — APPROVED** [review]
LGTM and it works when I try it locally.
There is conflict though, because I merged your other PR #358 just now. Can you rebase or merge?

**Comment by mauritsvanrees** [comment]
> Can you rebase or merge?

Never mind, I have fixed the conflict in the GitHub UI. Tests should be green again and then someone can merge.

**Comment by mauritsvanrees** [comment]
I have a weird problem now locally. `tox -e py38` works. `tox -e docs` works. After this, `tox -e py38` fails (same for the other Python versions. There are two kinds of errors.

```
__________________________________________________________________________________ ERROR collecting build/lib/icalendar/tests/hypothesis/test_fuzzing.py ___________________________________________________________________________________
ImportError while importing test module '/Users/maurits/community/plone-coredev/6.0/src/icalendar/build/lib/icalendar/tests/hypothesis/test_fuzzing.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Users/maurits/.pyenv/versions/3.8.12/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
build/lib/icalendar/tests/hypothesis/test_fuzzing.py:3: in <module>
    from hypothesis import given, settings
E   ModuleNotFoundError: No module named 'hypothesis'
__________________________________________________________________________________________ ERROR collecting src/icalendar/tests/test_encoding.py ___________________________________________________________________________________________
import file mismatch:
imported module 'icalendar.tests.test_encoding' has this __file__ attribute:
  /Users/maurits/community/plone-coredev/6.0/src/icalendar/build/lib/icalendar/tests/test_encoding.py
which is not the same as the test file we want to collect:
  /Users/maurits/community/plone-coredev/6.0/src/icalendar/src/icalendar/tests/test_encoding.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
```

The fix is: remove the `build` directory that was created by `tox -e docs`. Can you confirm this? Would you know a way around this?
Actually, I guess in the Makefile I can simply remove the `build` directory at the end, because this is not needed. Only `docs/_build/html` is needed. I will do that.

**Comment by niccokunzmann** [comment]
> Actually, I guess in the Makefile I can simply remove the build directory at the end, because this is not needed. Only docs/_build/html is needed. I will do that.

Ok.

**Pull request merged**
