### PR TITLE
Document how to access the documentation in the browser

### PR DESCRIPTION
**Pull request by niccokunzmann**
This is a nice add-on for maintainers.

### CODE REVIEW

**Review by stevepiercy — APPROVED** [review]
LGTM. Thank you!

**Comment by stevepiercy** [comment]
Oh, it needs a change log entry.

**Comment by stevepiercy** [comment]
Merge away!

**Comment by niccokunzmann** [comment]
@stevepiercy Do you have merge access?
You would probably count as a collaborator: https://icalendar.readthedocs.io/en/latest/maintenance.html#collaborators
What do you think?

**Comment by stevepiercy** [comment]
@niccokunzmann I'm a member of Collective, so I have write access and can merge PRs. I am still getting familiar with this library, but I have confidence with docs only to merge those PRs in the future.

As a side note, Collective is a very trusting organization, and it might be a good idea to restrict write access to only core contributors and other trustworthy folks for this one repository. Plone recently did that for its organization, mostly due to GSoC applicants doing bad things, like editing PLIPs. It also reduced risk if an unused or inactive account were to become compromised.

**Pull request merged**
