### PR TITLE
Document Setup process for development

### PR DESCRIPTION
**Pull request by niccokunzmann**
This pull request aims at clarifying how to setup icalendar for development.

### CODE REVIEW

**Comment by niccokunzmann** [comment]
@jenkins-plone-org please run jobs

**Comment by niccokunzmann** [comment]
So, I see this:

Plone Jenkins CI - pull-request-6.0-3.7:
```
Setup failed:
WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```

Much more... Is there some explanation for this? Why are all these tests running? Where can I read more about this?

**Comment by mauritsvanrees** [comment]
We should probably disable Jenkins tests for this package. We would need a replacement though. Last year I tried but failed to add [GitHub actions](https://github.com/collective/icalendar/pull/340).

I have created a [post on the Plone community forum](https://community.plone.org/t/future-of-icalendar-looking-for-maintainer/15445) about the future of this package, and needing a maintainer for it.

**Comment by geier** [comment]
We have set up GitHub actions for running tests for khal (which heavily relies on icalendar), I can give it a go.

**Comment by mauritsvanrees** [comment]
Actually, let me open op discussions in this repository: https://github.com/collective/icalendar/discussions/360

**Review by mauritsvanrees — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
