### PR TITLE
Added display method

### PR DESCRIPTION
**Pull request by TomTry**
Added display method to Calendar class as suggested in the docs

### CODE REVIEW

**Comment by untitaker** [comment]
"as suggested in the docs"?

**Comment by TomTry** [comment]
Here:

http://icalendar.readthedocs.org/en/latest/usage.html#overview

Is it not helpful?

**Comment by stlaz** [comment]
That's not really suggested, that's a strange example that's not really helpful I think? Is there a problem with just using `to_ical()`? I don't think there is.

**Comment by untitaker** [comment]
I'll close this. Thanks for the PR though!

**Pull request closed without merging**
