### PR TITLE
Categories to be comma separated list 

### PR DESCRIPTION
**Pull request by cleder**
see #263 for details

### CODE REVIEW

**Comment by cleder** [comment]
@esteele Any thoughts how to proceed?

**Comment by esteele** [comment]
I'm ok with this PR being merged.

How can we make sure that test gets fixed at some point?

**Comment by cleder** [comment]
#260 suggests that the test is actually wrong. I have never seen such complex examples in the wild and I am unlikely to put effort into testing of this edge case. 
Question is: do we NEED to cover this edge case or should it just be documented that this is currently not supported?

**Comment by jensens** [comment]
I am fine with this PR for now. As software development is incremental, another PR refining this may be needed.

**Pull request merged**
