### PR TITLE
add badges for download and PyPI version

### PR DESCRIPTION
**Pull request by niccokunzmann**
It adds two badges.

shows which version is there - quite useful to know and nice to see that it changes after deploy

makes sure we know that this is important and used a lot!

### CODE REVIEW

**Comment by geier** [comment]
While we are at it, should we remove the Travis Badge and also add a github workflow badge?

**Comment by geier** [comment]
Sorry, only saw #364 now.

**Comment by niccokunzmann** [comment]
No problem, nice to think alike.

**Review by Arhell — APPROVED** [review]

**Comment by geier** [comment]
@niccokunzmann  this now conflicts, do you want to resove or should I?

**Comment by niccokunzmann** [comment]
I can do it. It just takes a while.

**Review by mauritsvanrees — APPROVED** [review]

**Pull request merged**
