### PR TITLE
Drop syntax that was only required for py < 3.7

### PR DESCRIPTION
**Pull request by WhyNotHugo**
find . -iname "*.py" -exec pyupgrade --py37-plus {} \;

### CODE REVIEW

**Comment by niccokunzmann** [comment]
@WhyNotHugo It would go to the master branch - the 4.x branch keeps backward compatibility for fixes that people might want to apply.

**Comment by niccokunzmann** [comment]
I will notify you when the PR #381 is merged because that will create the tests so that we can test and merge fast instead of all this back and forth. Sorry for that!

**Comment by niccokunzmann** [comment]
merged as #376

**Comment by WhyNotHugo** [comment]
Oh, I think I misunderstood the intent of 4.x.

**Pull request closed without merging**
