### PR TITLE
Fix tests for dateutil 2.5

### LINKED ISSUE #194: Test failures with python-dateutil 2.5.3
When installing `python-dateutil==2.5.0` or newer, the tests fail:

    ======================================================================
    FAIL: test_tzinfo_dateutil (icalendar.tests.test_timezoned.TestTimezoned)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/tmp/guix-build-python-icalendar-3.9.2.drv-0/icalendar-3.9.2/src/icalendar/tests/test_timezoned.py", line 138, in test_tzinfo_dateutil
        self.assertTrue(date.tzinfo.__module__ == 'dateutil.tz')
    AssertionError: False is not true

    ----------------------------------------------------------------------
    Ran 84 tests in 0.165s

    FAILED (failures=1)

Using any older version seems to fix the problem.

cc @lfam

### PR DESCRIPTION
**Pull request by untitaker**
Fix #194

### CODE REVIEW

**Comment by geier** [comment]
lgtm

**Comment by untitaker** [comment]
@thet Could you release a new version? Thanks!

**Comment by stlaz** [comment]
It might be good to include at least https://github.com/collective/icalendar/pull/189 and https://github.com/collective/icalendar/pull/185/ for the next version but that's up to you ofc :)

**Comment by untitaker** [comment]
@thet Ping!

**Comment by thet** [comment]
@untitaker released

**Pull request merged**
