### PR TITLE
Fix Oss Fuzz Build Error

### PR DESCRIPTION
**Pull request by ennamarie19**
I'm currently working on switching the OSS Fuzz build to use the fuzzing harnesses hosted in icalendar. In doing that, I noticed that this change required updating the find path in the build.sh script. I tested it locally and the fuzz harnesses are able to build.

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Thanks!
Would you like to become a developer of icalendar? https://icalendar.readthedocs.io/en/latest/maintenance.html

**Comment by ennamarie19** [comment]
Thanks so much for the PR! That would be awesome. What role on that link did you have in mind? On Oct 29, 2023, at 4:48 AM, Nicco Kunzmann ***@***.***> wrote:﻿
Thanks!
Would you like to become a developer of icalendar? https://icalendar.readthedocs.io/en/latest/maintenance.html

**Comment by niccokunzmann** [comment]
I thought either "contributor" or "maintainer" - what would you like to step up to?

**Comment by ennamarie19** [comment]
Contributor would be great! Thank you Nicco! :) 
    On Tuesday, October 31, 2023 at 07:33:45 PM EDT, Nicco Kunzmann ***@***.***> wrote:  
 
 


I thought either "contributor" or "maintainer" - what would you like to step up to?

**Comment by ennamarie19** [comment]
Can I add your email to the auto-cc's so that you are copied on bug reports and fuzzing updates? Or is there a better one to add?
    On Wednesday, November 1, 2023 at 01:31:31 PM EDT, McKenna Dallmeyer ***@***.***> wrote:  
 
  Contributor would be great! Thank you Nicco! :) 
    On Tuesday, October 31, 2023 at 07:33:45 PM EDT, Nicco Kunzmann ***@***.***> wrote:  
 
 


I thought either "contributor" or "maintainer" - what would you like to step up to?

**Comment by niccokunzmann** [comment]
Maybe, one could add a github discussion. I am replying to this from another email address. If this is visible, one can add a new github discussion.

One thing that needs spreading in knowledge is how to deal with the tests failing and what it means.

**Comment by ennamarie19** [comment]
Well I need an email to add to the project.yaml hosted on OSS-Fuzz. Found here:  https://github.com/ennamarie19/oss-fuzz/blob/master/projects/icalendar/project.yamlI have an email of a past maintainer on there currently and he asked to be removed. I can definitely explain that. On Nov 2, 2023, at 5:10 AM, Nicco Kunzmann ***@***.***> wrote:﻿
Maybe, one could add a github discussion. I am replying to this from another email address. If this is visible, one can add a new github discussion.

One thing that needs spreading in knowledge is how to deal with the tests failing and what it means.

**Comment by niccokunzmann** [comment]
Hi, you could start a new discussion here: 
https://github.com/collective/icalendar/discussions/new?category=general

I will get an email and tell you the email address to add.

**Comment by niccokunzmann** [comment]
This is live in v5.0.11. Thanks for your contributions!

**Pull request merged**
