### PR TITLE
docs: Create an example for a component

### PR DESCRIPTION
**Pull request by prakrit55**
fixing #743

### CODE REVIEW

**Comment by prakrit55** [comment]
@niccokunzmann, we can have a discussion here.

**Comment by niccokunzmann** [comment]
This is the right place. Now, could you copy in an example from the rfc?

**Comment by prakrit55** [comment]
> This is the right place. Now, could you copy in an example from the rfc?

is there any way to generate rfc files, could you mention any way to do this

**Comment by stevepiercy** [comment]
@prakrit55 RFC stands for [Request for Comments](https://en.wikipedia.org/wiki/Request_for_Comments). The issue to be resolved would be to copy an example from the specific [RFC 5545](https://datatracker.ietf.org/doc/html/rfc5545.html) for one of the given components, and write a Python doctest for it in its method.

I'm not sure why the issue todo for each of the three checked `add src/icalendar/tests/todos/example.ics` is checked, because I don't see the [`todo` folder in the repo](https://github.com/collective/icalendar/tree/main/src/icalendar/tests) where it says it should be.

@niccokunzmann perhaps you could update the issue description with some more details? I'm not clear myself.

**Comment by prakrit55** [comment]
> @prakrit55 RFC stands for [Request for Comments](https://en.wikipedia.org/wiki/Request_for_Comments). The issue to be resolved would be to copy an example from the specific [RFC 5545](https://datatracker.ietf.org/doc/html/rfc5545.html) for one of the given components, and write a Python doctest for it in its method.
> 
> I'm not sure why the issue todo for each of the three checked `add src/icalendar/tests/todos/example.ics` is checked, because I don't see the [`todo` folder in the repo](https://github.com/collective/icalendar/tree/main/src/icalendar/tests) where it says it should be.
> 
> @niccokunzmann perhaps you could update the issue description with some more details? I'm not clear myself.

hello @stevepiercy, thanks for the reply, does the repo have any examples you can point me to

**Comment by niccokunzmann** [comment]
@prakrit55, could you have a look at the documentation and the file structure and the issue - the issue points towards

- [x] what has been done already

Then, please ask again.

@stevepiercy, I will write more into the issue now.

**Comment by niccokunzmann** [comment]
Thanks for your effort. I will close this now. Feel free to open an new one.

**Pull request closed without merging**
