### PR TITLE
Fixed small typos

### PR DESCRIPTION
**Pull request by rohnsha0**
as described in #323

### CODE REVIEW

**Review by niccokunzmann — APPROVED** [review]
nice!

**Comment by niccokunzmann** [comment]
@rohnsha0 Thanks!
If you want the issue to close autimatically when this is merged, write 'fixes #323' in the PR body.

**Comment by rohnsha0** [comment]
> nice!

Haha! Thanks!

**Comment by rohnsha0** [comment]
> @rohnsha0 Thanks! If you want the issue to close autimatically when this is merged, write 'fixes #323' in the PR body.

Sure... From next time!

**Pull request merged**
