### PR TITLE
Added more instrumentation + caught one more exception

### PR DESCRIPTION
**Pull request by ennamarie19**
Another quick PR, I added another defined exception that was holding up fuzzer progress and made a tweak to see if we can get more intelligent instrumentation and coverage exploration. 

A suggestion would be collecting all raised exceptions under a common base-class, such as CalendarException, so the fuzzer can just do except CalendarException as opposed to string-matching multiple ValueErrors. This would also help users of the library in their error-handling, as well.

### CODE REVIEW

**Comment by niccokunzmann** [comment]
> A suggestion would be collecting all raised exceptions under a common base-class, such as CalendarException, so the fuzzer can just do except CalendarException as opposed to string-matching multiple ValueErrors. This would also help users of the library in their error-handling, as well.

tht sounds good, I would keep the base classes and put them all into exceptions.py

**Comment by niccokunzmann** [comment]
you already created fixes. feel free to follow the release process to release a new version

**Comment by capuanob** [comment]
> you already created fixes. feel free to follow the release process to release a new version

Good morning,

Could you explain what you mean? Are you asking us to bump the version number due to this PR?

Thank you!

**Comment by niccokunzmann** [comment]
I think, there were some fixes made in other PRs.

Independent of this: If you like to release a new version, you can follow the release process: https://icalendar.readthedocs.io/en/latest/maintenance.html - solely as information, to give you a choice!

**Pull request merged**
