### PR TITLE
Drop python2-compat module

### PR DESCRIPTION
**Pull request by WhyNotHugo**

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Cool. There seem to be a few more imports, judging from the test failure.

**Comment by WhyNotHugo** [comment]
Fixed.

**Comment by niccokunzmann** [comment]
Thanks! Are you in the contributors file?
Also, do you think, this would be useful in the changelog? I do not know at the moment, what our changelog policy is.

**Comment by WhyNotHugo** [comment]
> Thanks! Are you in the contributors file?

I think not, I'll add myself in the next PR.

>  Also, do you think, this would be useful in the changelog? I do not know at the moment, what our changelog policy is.

Not really. Dropping support for Python2 is already documented, this is just housekeeping.

**Pull request merged**
