### PR TITLE
Update parser.py

### PR DESCRIPTION
**Pull request by N0ury**
issue #348

### CODE REVIEW

**Review by jacadzaca — APPROVED** [review]

**Comment by jacadzaca** [comment]
thanks for contributing :) we'll merge when #500 gets merged, so the tests are green.

**Comment by jacadzaca** [comment]
@N0ury could you please add yourself to the credits and add a changelog entry as per [CONTRIBUTING](https://github.com/collective/icalendar/blob/master/CONTRIBUTING.rst)? Thanks for the contribution once again :)

**Comment by niccokunzmann** [comment]
#501 has been merged. If the master branch is merged into this one, the tests should be green again.

**Comment by niccokunzmann** [comment]
I wonder if this fixes the tests from #436.

**Pull request merged**
