### PR TITLE
add icalendar file from issue #314 and parse it

### PR DESCRIPTION
**Pull request by niccokunzmann**
This is a pull request to test and fix https://github.com/collective/icalendar/issues/314.

### CODE REVIEW

**Comment by jacadzaca** [comment]
I don't find a test without an assertion correct.

**Comment by niccokunzmann** [comment]
Maybe we just close this and the issue.

**Comment by niccokunzmann** [comment]
The tests show that the example cannot be reproduced any more.

But, it might be worth checking that the standard does not allow DATE as type. Then, this PR can be modified.

**Comment by niccokunzmann** [comment]
Well, that might be an issue in the future. I think, we can close this and the issue as the faulty implementation removed cause of the error. Thanks for the review!

**Pull request closed without merging**
