### PR TITLE
add test case for unit prop

### PR DESCRIPTION
**Pull request by raffifu**
This PR resolve https://github.com/collective/icalendar/issues/605

When adding test case, i still can't figured it out how to trigger __repr__ function. Could you help me with guidance to trigger that?

# Improvement
Screenshot_11-Jun-2024_22-23-18

### CODE REVIEW

**Comment by niccokunzmann** [comment]
@raffifu, you can use `repr()` on the object.
Thanks for your contribution!

**Comment by niccokunzmann** [comment]
Would you like to add `improve test coverage` to the changelog in your PR?

**Comment by raffifu** [comment]
@niccokunzmann i already add `improve test code` into changelog

**Comment by niccokunzmann** [comment]
@raffifu Thanks for this PR!

**Pull request merged**
