### PR TITLE
UTC-fix + zoneinfo-fix

### PR DESCRIPTION
**Pull request by tobixen**
This is a combination of merge request #334 and merge request #337.

If all tests pass, then it must be a temporarily glitch that merge request #334 didn't pass.

If there are the same test failures as in request #334, then ... probably that merge request breaks plone somehow.

Sorry for the flood of merge-requests.  Don't know how to run those plone tests.  I'm just interested in the icalendar library :-)

### CODE REVIEW

**Comment by tobixen** [comment]
@jenkins-plone-org please run jobs

**Comment by tobixen** [comment]
@jenkins-plone-org please run jobs

**Comment by tobixen** [comment]
Uff - the failures now is due to the last bugfix, fixing a bug in the new test code.

**Comment by tobixen** [comment]
@jenkins-plone-org please run jobs

Trying to rerun tests ... as I still believe the test breakages are arbitrary and not related to my changes

**Comment by niccokunzmann** [comment]
@tobixen , we are in the process of setting up maintenance for this repository again, see #360. It will take some time but I hope, we will get further towards integrating your changes. Thanks a lot for the effort and patience already!
If you like to run the latest tests for this PR, you can rebase/merge master.

**Comment by niccokunzmann** [comment]
Thanks @tobixen! That is a nice PR with a lot of tests!

**Pull request merged**
