### PR TITLE
Drop support for Python2

### PR DESCRIPTION
**Pull request by WhyNotHugo**
My intent is to use `ZoneInfo` instead of `pytz`.

The former is part of the standard library as of Python 3.9, and there's a [backport library](https://pypi.org/project/backports.zoneinfo/) for all currently supported Python versions.

However, this requires dropping support for Python 2. I initially though of doing everything at once, but given the current size of these changes so far, I think it's preferring to open a PR for this part, and address the rest in a followup.

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
@jenkins-plone-org please run jobs

**Comment by WhyNotHugo** [comment]
Huh, job run in CI don't seem to match what my branch (or master) has defined. The only thing I see in-repo is `.travis.yml`, but nothing Jenkins-related.

**Comment by WhyNotHugo** [comment]
Oh, I only saw the travis definitions on this repo, I wasn't aware of the external jenkings pipline set up here.

Is this PR actually viable, or is support for Python2 something that you need to support?

**Comment by aleksihakli** [comment]
@WhyNotHugo I was just checking the PR I made a while back, there's also some work on dropping Python 2.7 support in #292

**Comment by niccokunzmann** [comment]
@WhyNotHugo, thanks for submitting this! The master branch now works on Python 3.8+ Would you like to close this?

**Comment by WhyNotHugo** [comment]
I've rebased this onto the current master. There's still a lot of python2-specific code, and references to python 2.7, 3.6 and 3.7. Are these two also not supported any longer>

**Comment by WhyNotHugo** [comment]
Tox is still set up to run py27, and setup.py has outdated trove classifiers and python version.

**Comment by niccokunzmann** [comment]
There is #366 which if merged removes some backward compatibility requirements and there other PRs pending. Thanks for responding! It will take some time until the development picks up speed again. I am happy to receive some links to what else would need changing from your perspective - though at the moment, I cannot promise when someone will come back to that..

In #360 we discuss the new maintenance of this repository, if you are interested.

**Comment by WhyNotHugo** [comment]
Rebased again. Happy to see this under active maintenence again!

**Comment by mauritsvanrees** [comment]
Looks okay at first glance. But I have enabled running the gh-actions workflow, and it fails.

I don't know why you say in the changelog "Added support for Python 3.9 and 3.10." This support has been there for a long time. Maybe a left-over from an earlier version of your PR.

Or should this PR be closed and should we only look at your PR #376 instead.

**Comment by WhyNotHugo** [comment]
Most of this has been merged via smaller PRs and the last bits are in https://github.com/collective/icalendar/pull/385

**Pull request closed without merging**
