### PR TITLE
Remove VALUE=DATE-TIME from DTSTART, DTEND, DTSTAMP

### PR DESCRIPTION
**Pull request by niccokunzmann**
This adds tests for #318.

If you like to fix them - please check out the branch `issue-318-skip-value-parameter-for-default-date-time` add some code and create a pull request to `issue-318-skip-value-parameter-for-default-date-time`.

### CODE REVIEW

**Comment by jacadzaca** [comment]
@niccokunzmann will you add a changelog?

**Comment by niccokunzmann** [comment]
CHANGELOG. Ok, is a todo.

The communicative purpose of the plone tests is to notify the plone developers about potential problems of a certain release. Other projects use version fixing. The plone tests intoduce a new dimension of knowledge that is required to make icalendar green but not required to make it work.
I have three projects depending on icalendar. I cannot ask icalendar developers to engage with my tests.

I would like to ship this to master so that they can fix their tests fast.

**Comment by jacadzaca** [comment]
I think we shouldn't break peoples' tests on the weekend, but it's you to you

**Comment by niccokunzmann** [comment]
It will take a while until I have the changelog. Tests broken is not production code broken. If it is, it must be changed.

Making progress here dependent on the plone tests and the other 1000 projects for that matter that use Icalendar, introduces a complexity that will kill this project - I guess - again.

I do not merge it now but would like to propose a process where we notify plone on release about breaking tests. They will use version-fixing `icalendar==5.0.3` for example. Dependabot will bring updates, then.

**Comment by niccokunzmann** [comment]
Looking at the tests, only their tests need changing.

**Comment by niccokunzmann** [comment]
@mauritsvanrees The plone tests are failing on this one. They require simple changes.

**Comment by mauritsvanrees** [comment]
I have merged my `plone.app.event` PR and am now rerunning the failed job here.

**Comment by mauritsvanrees** [comment]
Green!
Only a changelog entry is missing now.

**Comment by niccokunzmann** [comment]
Merged and CHANGELOG is modified.

**Review by mauritsvanrees — APPROVED** [review]

**Pull request merged**
