### PR TITLE
Updated components to better conform to RFC 5545

### PR DESCRIPTION
**Pull request by stlaz**
https://github.com/collective/icalendar/issues/176

======
Should we ever get the strict mode described in https://github.com/collective/icalendar/issues/28, the properties description here needs to be correct. RFC5545 is not so easily readable so some of the properties might still be missing even in this patch. I should hope not, though.

### CODE REVIEW

**Comment by thet** [comment]
Looks good to me!

**Comment by mauritsvanrees** [comment]
Coredev 5.0 tests are broken after this: http://jenkins.plone.org/job/plone-5.0-python-2.7/4630/

There are two failures in plone.app.event, for example this one:

```
menu item "RRULE:FREQ=DAILY;COUNT=3;INTERVAL=1" missing or out of order

  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/home/jenkins/workspace/plone-5.0-python-2.7/src/plone.app.event/plone/app/event/tests/test_icalendar.py", line 84, in test_event_ical
    'END:VCALENDAR')
  File "/home/jenkins/workspace/plone-5.0-python-2.7/src/plone.app.event/plone/app/event/tests/test_icalendar.py", line 37, in checkOrder
    'menu item "%s" missing or out of order' % item
  File "/usr/lib/python2.7/unittest/case.py", line 424, in assertTrue
    raise self.failureException(msg)
```

Can you have a look?

**Comment by mauritsvanrees** [comment]
BTW, coredev 5.1 is also broken, in the same tests.

**Comment by thet** [comment]
Tnx for the pointer! that was just different ordering of the output, which we checked. Fixed in both 5.0 and 5.1

**Pull request merged**
