### PR TITLE
change assertRaisesRegexp to assertRaisesRegex

### PR DESCRIPTION
**Pull request by tuergeist**

### CODE REVIEW

**Comment by tuergeist** [comment]
Python 2.7 test failed. but Python 2.7 is at the end of life

**Comment by geier** [comment]
rebasing on master and closing and reopening to get tests to re-run

**Review by geier — APPROVED** [review]

**Comment by niccokunzmann** [comment]
This can probably be merged when Python 2 support is over. Also, PR #330 looks like related work.

**Comment by niccokunzmann** [comment]
Thanks!

**Pull request merged**
