### PR TITLE
Bugfix for datetime objects with tzinfo from zoneinfo library

### PR DESCRIPTION
**Pull request by tobixen**
See https://github.com/collective/icalendar/issues/333 for details

Includes test code and changelog entry

(but the test code includes a lot of copy&paste - perhaps it should be refactored?)

### CODE REVIEW

**Comment by tobixen** [comment]
@jenkins-plone-org please run jobs

**Comment by tobixen** [comment]
Silly me.

@jenkins-plone-org please run jobs

**Comment by tobixen** [comment]
I feel quite confident that the test breakages above has nothing to do with my changes.

**Comment by tobixen** [comment]
Can I rerun the tests?

@jenkins-plone-org please run jobs

**Comment by tobixen** [comment]
@jenkins-plone-org please run jobs

**Comment by tobixen** [comment]
Different failures now than last time.  I rest my case ... those errors seems to be arbitrary and not related to my merge request.

**Comment by tobixen** [comment]
@jenkins-plone-org please run jobs

**Comment by tobixen** [comment]
@jenkins-plone-org please run jobs

**Comment by geier** [comment]
rebased on master, closing and re-opening to get test to run

**Comment by niccokunzmann** [comment]
Now that the tests ran, the merge conflicts need to be resolved.

**Comment by tobixen** [comment]
This one seems moot, as #338 has been merged into master.

**Pull request closed without merging**
