### PR TITLE
Fix ResourceWarnings in setup.py when Python warnings are enabled

### PR DESCRIPTION
**Pull request by jdufresne**
Always explicitly close files. Use a context manager to make this easier.

### CODE REVIEW

**Comment by untitaker** [comment]
Idk, could you change this to something like:

```
for fname in ('README.rst', 'CHANGES.rst', ...):
    with codecs.open(fname, ...):
        ...
```

**Comment by jdufresne** [comment]
Made suggested update.

**Comment by jdufresne** [comment]
The commit is marked as a failure by "Changelog verifier". Am I expected to add an entry for this? I don't think it really affects users when upgrading.

**Comment by untitaker** [comment]
Thanks! No worries.

**Pull request merged**
