### PR TITLE
Fix non-ascii TZID and TZNAME handling in python 2

### PR DESCRIPTION
**Pull request by clivest**
Following on from #237, I realised this problem only occurs when using python 2. I've done the inexact conversion to str only when running in python 2. This retains the full zone name in python 3 but unfortunately makes timezone handling slightly different when running in different python versions. What do you think?

### CODE REVIEW

**Comment by clivest** [comment]
Sure, thanks!

> I'm so ready for dropping python 2 support

Yeah. Shame some of us still have to live in the past

**Comment by geier** [comment]
Since nobody else had a look and it's been months, I just merged this. Thanks again for your effort!

**Comment by clivest** [comment]
@geier Thanks for merging! Is there plans for another release?

**Comment by geier** [comment]
@clivest I have know idea how releases are done, sorry. But they are made rather regular.

**Comment by thet** [comment]
@clivest @geier release done: https://pypi.python.org/pypi/icalendar/3.12

**Comment by geier** [comment]
Thanks!

Quoting Johannes Raggam (2017-11-07 10:15:25)

**Comment by clivest** [comment]
Thanks

**Pull request merged**
