### PR TITLE
display file content of example

### PR DESCRIPTION
**Pull request by abe-101**
I suggest it might be a nice idea to display the content of the file generated in the example

### CODE REVIEW

**Comment by jacadzaca** [comment]
Could you try to make the [expected output be tested](https://github.com/collective/icalendar/blob/master/src/icalendar/tests/test_with_doctest.py)? This way the documentation wont become stale.

**Comment by abe-101** [comment]
> Could you try to make the [expected output be tested](https://github.com/collective/icalendar/blob/master/src/icalendar/tests/test_with_doctest.py)? This way the documentation wont become stale.

Done.
doctest are new to me but I think it should be good now

**Review by jacadzaca — APPROVED** [review]

**Comment by jacadzaca** [comment]
Thanks!

**Comment by jacadzaca** [comment]
Personally, I'd make the commit message more detailed, e.g. `show generated example's content on the usage page`, but it's a nitpick.

**Pull request merged**
